### ISSUE TITLE
Install fails with any timezone

### ISSUE THREAD

**Issue by fethomm** [Nitrux/nitrux-bug-tracker#100]
**Describe the bug**
Install of Nitrux 2.8 (in Proxmox, which should not matter for this issue) fails with an error regarding timezone. First I chose EUROPE/BERLIN, and it failed. Then I used AMERICA/ANCHORAGE and it failed to install as well. The error message is that is shown in the screenshot says:
Failed to access the path of the selected time zone.
Details:
Invalid path: /tmp/calamares-root-c9nti5r7/usr/share/zoneinfo/Europe

**To Reproduce**

**Expected behavior**
Installation going through to the end

**Screenshots**

**Desktop (please complete the following information):**
 - OS Proxmox (Debian)
 - Browser 
 - Version
![timezone failed](https://user-images.githubusercontent.com/15143037/235417690-b1acf5a0-961d-4967-ad43-0a251e236630.jpeg)

**Additional context**

**Comment by UriHerrera** [comment]
Please provide the log of Calamares when the error occurs. Also, if possible, what configuration are you using in Proxmox?

**Comment by fethomm** [comment]
I will get you the information later today or tomorrow. What I can tell you now is that the same thing happens in VirtualBox.

**Comment by UriHerrera** [comment]
I installed the distribution on VirtualBox and there weren't any problems setting the timezone, the localecfg module in Calamares does its job.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3053525/235438522-702e8fbb-2157-49b1-9909-ada641adcb8a.gif)

I have also tested with select Deutsch as the language, Berlin as the timezone and US keyboard, then Erase disk. There also no problems.

**Comment by UriHerrera** [comment]
> Having the same problem. Don't know how to get log.

With `sudo -E calamares -d`. This is mentioned in the [Notes](https://nxos.org/notes/notes-nitrux-2-8-0/).

**Comment by UriHerrera** [comment]
I have been able to reproduce the problem on VirtualBox.

![VirtualBox_VBox Default Settings_07_05_2023_01_58_31](https://user-images.githubusercontent.com/3053525/236665406-3ac3843a-65c1-4209-93b7-a8b867f7b6cd.png)

I have used the default settings on a new VM, except for settings for setting the virtual CPU cores to two.

![imagen](https://user-images.githubusercontent.com/3053525/236665589-a13598c8-d92e-4b4a-af07-e676eb1931e4.png)

I created an 8GB VDI for this VM, and that's precisely the problem.

What problem? The problem is that the virtual storage device is too small.

In the [Notes](https://nxos.org/notes/notes-nitrux-2-8-0/#installing-nitrux), we link to our tutorial to install the distribution. This tutorial details the amount of necessary storage the root partition should have.

Anything less and, of course, Calamares fails to extract the SquashFS. However, this also applies to physical storage. If the root partition isn't big enough, the installation *will fail*.

But what if the device is 9GB? Nope. Please take a look at the image below.

The root (NX_ROOT) is only 1.78 GiB (or 1.91GB); that's too small.

![VirtualBox_VBox Default Settings_07_05_2023_02_30_20](https://user-images.githubusercontent.com/3053525/236666833-8a3a6e20-8631-434b-bf30-7daa7bc78b5d.png)

The thing is that Calamares doesn't say anything about it, and that's apparently because the default settings of a new VM make it boot using Legacy BIOS, not EFI. When the user sets EFI in the VM, Calamares will display an error regarding rsync, specifically, error 10. I don't know why.

So yeah, please do not use the default settings for a VM. The [Notes](https://nxos.org/notes/notes-nitrux-2-8-0/#virtualizing-nitrux) have concrete recommendations; please read them (and, in general, read the Notes).

As is, the problem is solved by having a big enough root partition.
