### ISSUE TITLE
Can't boot the Live ISO from Ventoy

### ISSUE THREAD

**Issue by RaptaG** [Nitrux/nitrux-bug-tracker#104]
**Describe the bug**
When placing the Nitrux .iso file inside a Ventoy USB stick you can't boot into the live enviroment

**To Reproduce**
1. Install the Nitrux ISO inside a Ventoy USB stick
2. Boot from the USB into your computer
3. Select the Ventoy ISO to boot in normal mode

**Expected behavior**
Being able to boot from a Ventoy USB

**Screenshots**
I will add photos tomorrow

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38
 - Browser: LibreWolf latest

**Additional context**
Similar to https://github.com/Nitrux/nitrux-bug-tracker/issues/25. Also I'm really sorry for the ping spam there, I didn't mean to annoy. I'll provide more technical information tomorrow.

**Comment by UriHerrera** [comment]
Which version of Ventoy are you using? I have tested Ventoy 1.0.91 on a 32GB USB thumbdrive with our latest ISO, and booting the ISO works if I select `boot in grub 2 mode`.

![imagen](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/d9d8c299-2795-4765-8db5-18692745fc2b)

Even if I have used GPT to install Ventoy to the USB, if I boot the ISO on a Legacy BIOS computer, the appropriate option loads.

![photo_2023-05-20_16-26-36](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/ef1ac36a-230c-447f-a795-ae59cfb0d4f5)

**Comment by RaptaG** [comment]
So here's the full process:

![](https://github.com/Nitrux/nitrux-bug-tracker/assets/77157639/8f0d0701-e24b-428f-9e37-401b58162153)

![](https://github.com/Nitrux/nitrux-bug-tracker/assets/77157639/84e1a353-2317-4e6e-bb8a-dd40ef78db31)

![](https://github.com/Nitrux/nitrux-bug-tracker/assets/77157639/b56722d9-9d35-4c71-9ace-2ef0049802c0)

![](https://github.com/Nitrux/nitrux-bug-tracker/assets/77157639/2fdd825d-a54e-43f6-8888-80cf184a0f1d)

**Comment by RaptaG** [comment]
I even updated Ventoy to the latest version, still the same error

**Comment by UriHerrera** [comment]
@RaptaG That's a kernel panic. Could you add your computer specifications? You can see in your image it says `/init: not found` Did you verify the checksum of the ISO? Are **sure** that the ISO in your USB was copied __correctly__?

**Comment by UriHerrera** [comment]
@RaptaG That's a kernel panic. Could you add your computer specifications? You can see in your image it says `/init: not found` Did you verify the checksum of the ISO? Are you **sure** that the ISO in your USB was copied __correctly__?

![imagen](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/9ba723ec-da7e-4bf7-b757-31c4fb738890)

Also, could you verify that the ISO file size is 3324456960 bytes?

![imagen](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/eca03489-e5be-4864-bd21-d7a7dbe26957)

---

How did you copy the file? Since you don't mention what size your USB is or other specifications, I assume you simply copied it or dragged and dropped the file to the USB using Nautilus (since you mentioned Fedora). Our ISO is 3.3GB (or 3.1GB according to OSDN 🤷🏾; I think they meant GiB or Gibibytes ); large files take time to be written to the physical storage. I do not know if your USB device is USB 2.0 or 3.0, 3.1, etc.

It seems to me that you removed the device before the file was written to the storage, be aware that there's a write cache, and in devices with little cache or no cache at all (as are most USB thumb drives), that cache needs to be flushed __completely__ before data is on the storage proper. Using the command `sync` will precisely do that.

On our [tutorial to install the distribution](https://nxos.org/tutorial/how-to-install-nitrux/), the command to flash the ISO using `dd` includes an option to tell `dd` to flush the write cache, `oflag=sync`, for that reason. Since Ventoy is not used to adding the ISO files but booting them, I'd argue that it's also not a problem with Ventoy.

**Comment by RaptaG** [comment]
Forgot to update the status of this: The installation was corrupted, I re-installed the `.iso` and the issue got fixed!

PS: I'd suggest you don't close issues like this...
