### ISSUE TITLE
Installation succesful but installed system does not work

### ISSUE THREAD

**Issue by itzdrli** [Nitrux/nitrux-bug-tracker#128]
**Description:**

After successfully installing the Nitrux OS 2.9.1, I am encountering an issue where I cannot start the system.

**To Reproduce:**

1. Boot into the live system using Ventoy.
2. Proceed with the system installation using the standard method.
3. After installing, perform a system restart and enter the installed OS.
4. An error message is displayed, preventing the system from starting.

**Expected Behavior:**

The system should start with the graphical user interface (GUI) as intended.

**Screenshots:**

![Error Screenshot](https://github.com/Nitrux/nitrux-bug-tracker/assets/52338732/2937883f-6a41-4617-83ee-91e11558e99d)
![photo_2023-08-13_13-05-29](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/96408cfb-9da0-400a-b95f-52915fc2aaa2)
![photo_2023-08-13_12-05-10](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/a2ec537c-86d2-44ea-b11d-f25fea29dc37)

**System Information:**

- Operating Systems: Windows 11 & Nitrux OS 2.9.1

**Additional Context:**

I have attempted a reinstallation, but the issue persists. I have also tried replacing the partition and manually partitioning during installation.

I've also tried to start a graphical session using these commands:

```
startplasma-wayland
startplasma-x11
```

However, I get the following error:

```
XDG_RUNTIME_DIR not set, defaulting to /tmp/runtime-root
Error creating runtime dictionary/tmp/runtime-root (read-only file system)
$DISPLAY is not set or cannot connect to the X server
From QStandardPaths
```

**Hardware Probe:**

For additional information about the hardware configuration (gathered from a different OS on the same computer), you can refer to the following hw-probe URL: [Hardware Probe](https://linux-hardware.org/?probe=7b7a62d5fb). 

This might provide insights into any potential hardware-related compatibility issues.

**Comment by UriHerrera** [comment]
@itzdrli I've edited the text of your issue to be more precise.

By the way, the Hardware Probe URL you provided is from a VM; please provide a valid URL from the system where you're having the problem.

Also, include the following:

- /var/log/rc.log
- /var/log/dmesg
- /var/log/boot.log
- /var/log/syslog

**Comment by itzdrli** [comment]
> @itzdrli I've edited the text of your issue to be more precise.
> 
> By the way, the Hardware Probe URL you provided is from a VM; please provide a valid URL from the system where you're having the problem.
> 
> Also, include the following log files:
> 
>     * /var/log/rc.log
> 
>     * /var/log/dmesg
> 
>     * /var/log/boot.log
> 
>     * /var/log/syslog

Hi, thanks for responding. So the hw proble URL, I can't get it from nitrux i've installed, the system kept saying `cannot do something: read-only file system.` and so on.
and about the log files, I don't know why but I can't find neither of them in /var/log. I think it's because of the `read-only filesystem` too?

**Comment by UriHerrera** [comment]
@itzdrli, If the log files persist on the root directory, you can access them from a Live session. Create a directory to mount the root and grab the files.

```
sudo mkdir /media/chroot-root
sudo mount -t auto $(findfs LABEL=NX_ROOT) /media/chroot-root
```

If they're not in the root directory or the files are empty, you can boot the installation and take a photo of the content; only ensure the photos are clear, e.g., login as your user and use `micro` to open the files and navigate the content using the text editor.

You can do this for the following files.

- `/etc/fstab`
- `/etc/passwd`
- `/etc/group`
- `/etc/default/grub`
- `/etc/hostname`
- `/boot/grub/grub.cfg`

Another thing is that in the screenshots you shared on the Telegram group, I noticed that the shell was not using the proper theme, and the hostname said `(none)`  _Note: I've attached these photos to your issue and also added the extra information you mentioned when you tried to start a graphical session_.

Additionally, on one of your screenshots, you can see only a single mount point, `/media/root-ro` where there's nothing else mounted, including your home directory.

So that you know, these should be the mounting points.

![imagen](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/3ddd9e2e-6a42-4463-9167-be4230c04da9)

---

However, I'd like to see where the problem is coming from originally since the Live session is working fine for you. I will ask you to do a reinstall if you don't mind if you don't mind. However, could you record a video of the whole installation process? It would be best to do manual partitioning following the steps in the installation tutorial.

On the Live session, open Station and run `sudo -E calamares -D6`, then click the button in the image to display the installation log while Calamares is running.

![Screenshot_20230815_113732](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/58118427-c0f8-4a4c-afa2-734861f326a7)

> GitHub doesn't allow video uploading, upload it somewhere and share the URL.

While In the Live session, grab the file `~/.cache/calamares/session.log` and attach it to the issue after the installation completes.

Then, you can just navigate to the newly created root partition, which should be visible on the sidebar in Index. 

![Screenshot_20230815_114249](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/0eb03c30-039a-40bb-863c-f9659b1b8375)

The root partition should match the temporary directory name used by Calamares. Since it's a temporary name, the last sequence of characters will be different every time.

![Screenshot_20230815_114420](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/35c78c13-9b45-457c-a0bd-5df43400a3b3)

While you navigate the installation's root directory, grab the following files and attach them to the issue.

- `/etc/fstab`
- `/etc/passwd`
- `/etc/group`
- `/etc/default/grub`
- `/etc/hostname`
- `/boot/grub/grub.cfg`

**Comment by itzdrli** [comment]
> @itzdrli, If the log files persist on the root directory, you can access them from a Live session. Create a directory to mount the root and grab the files.
> 
> ```
> sudo mkdir /media/chroot-root
> sudo mount -t auto $(findfs LABEL=NX_ROOT) /media/chroot-root
> ```
> 
> If they're not in the root directory or the files are empty, you can boot the installation and take a photo of the content; only ensure the photos are clear, e.g., login as your user and use `micro` to open the files and navigate the content using the text editor.
> 
> Use Alt+Q to quit the editor.
> 
> You can do this for the following files too.
> 
>     * `/etc/fstab`
> 
>     * `/etc/passwd`
> 
>     * `/etc/group`
> 
>     * `/etc/default/grub`
> 
>     * `/etc/hostname`
> 
>     * `/boot/grub/grub.cfg`
> 
> 
> Another thing is that in the photos you shared on the Telegram group, I noticed that the shell was not using the proper theme, and the hostname said `(none)`
> 
> > _Note: I've attached these photos to your issue and added the extra information you mentioned when you tried to start a graphical session_.
> 
> Additionally, on one of your photos, you can see only a single mount point, `/media/root-ro`, where there's nothing else mounted, including your home directory.
> 
> So that you know, these should be the mounting points. In my case, I'm using an encrypted home partition.
> 
> ![imagen](https://user-images.githubusercontent.com/3053525/260810806-3ddd9e2e-6a42-4463-9167-be4230c04da9.png)
> 
> However, I'd like to see where the problem is coming from initially since the Live session is working fine for you. I will ask you to do a reinstall if you don't mind. However, could you record a video of the whole installation process? It would be best to do manual partitioning following the steps in the installation tutorial.
> 
> On the Live session, open Station and run `sudo -E calamares -D6`, then click the button in the image to display the installation log while Calamares is running.
> 
> ![Screenshot_20230815_113732](https://user-images.githubusercontent.com/3053525/260791142-58118427-c0f8-4a4c-afa2-734861f326a7.png)
> 
> > GitHub doesn't allow video uploading, upload it somewhere and share the URL.
> 
> While In the Live session, grab the file `~/.cache/calamares/session.log` and attach it to the issue after the installation completes.
> 
> Then, you can just navigate to the newly created root partition, which should be visible on the sidebar in Index.
> 
> ![Screenshot_20230815_114249](https://user-images.githubusercontent.com/3053525/260793345-0eb03c30-039a-40bb-863c-f9659b1b8375.png)
> 
> The root partition should match the temporary directory name used by Calamares. Since it's a temporary name, the last sequence of characters will be different every time.
> 
> ![Screenshot_20230815_114420](https://user-images.githubusercontent.com/3053525/260793515-35c78c13-9b45-457c-a0bd-5df43400a3b3.png)
> 
> While you navigate the installation's root directory, grab the following files and attach them to the issue.
> 
>     * `/etc/fstab`
> 
>     * `/etc/passwd`
> 
>     * `/etc/group`
> 
>     * `/etc/default/grub`
> 
>     * `/etc/hostname`
> 
>     * `/boot/grub/grub.cfg`

thanks, I cloudn't record a video for some reasons, but I took screenshots and copied files you need:
![Screenshot_20230815_205747](https://github.com/Nitrux/nitrux-bug-tracker/assets/52338732/b2ecf0b3-f8c4-4396-bfa0-8f9aa05cdc73)
files: 
[nx.zip](https://github.com/Nitrux/nitrux-bug-tracker/files/12352686/nx.zip)

**Comment by itzdrli** [comment]
Hi, any updates please?

**Comment by UriHerrera** [comment]
> Hi, any updates please?

Your logs post-installation all seem fine. I think that to have more insight, it'd be necessary to see the logs once the system boots, mainly because I mentioned that the partitions are not mounted.

**Comment by itzdrli** [comment]
> 

based on the system is currently a "read-only" system, how can I get the log when system boots?

**Comment by UriHerrera** [comment]
> > 
> 
> based on the system is currently a "read-only" system, how can I get the log when system boots?

When you're at the GRUB menu, press <kbd>E</kbd> and navigate until you find the list of kernel parameters, then remove `quiet`, and press <kbd>F10</kbd> to continue booting. When the boot splash appears, press <kbd>Esc</kbd> to visualize the output of OpenRC.

Please make sure to record the whole process.

Once the installation boots, login to a TTY; you should still be able to visualize these files even in the state of your installation.

- `/etc/fstab`
- `/etc/passwd`
- `/etc/group`
- `/etc/default/grub`
- `/etc/hostname`
- `/boot/grub/grub.cfg`

**Comment by itzdrli** [comment]
> > > 
> > 
> > 
> > based on the system is currently a "read-only" system, how can I get the log when system boots?
> 
> When you're at the GRUB menu, press E while the default menu entry is highlighted and navigate until you find the list of kernel parameters, then remove `quiet`, and press F10 to continue booting. When the boot splash appears, press Esc to visualize the output of OpenRC.
> 
> Please make sure to record the whole process.
> 
> Once the installation boots, login to a TTY; you should still be able to visualize these files even in the state of your installation.
> 
>     * `/etc/fstab`
> 
>     * `/etc/passwd`
> 
>     * `/etc/group`
> 
>     * `/etc/default/grub`
> 
>     * `/etc/hostname`
> 
>     * `/boot/grub/grub.cfg`

Thanks, but today I switched to another usb falshdrive and reinstalled the system, now it strangely worked with no reason. So now the issue is solved, thanks for all the help
