### ISSUE TITLE
Live ISO boots to blank screen when using the Nvidia proprietary drivers

### ISSUE THREAD

**Issue by ayvind** [Nitrux/nitrux-bug-tracker#14]
**Describe the bug**
Booting into the Live USB image, the screen goes black. It happens when trying to load X11. A short press on the power button and the login manager is re-instated, and x now seems to work fine. I suspect most people won't figure this one out, though.

**To Reproduce**
I use a USB stick to load the live installer. I flashed with Etcher.

**Expected behavior**
Enter the Live environment without a login request.

Video of the bug occurrence https://www.youtube.com/watch?v=DhF0IIXf61s

Intel Core i5-8250U 1.6ghz
Nvidia GeForce MX150
8GB RAM
ASUS UX430U

**Comment by UriHerrera** [comment]
I can't reproduce this bug, can you provide any video of the occurrence?. Also, what are your hardware specifications.

**Comment by ayvind** [comment]
documenting this bug on video [https://www.youtube.com/watch?v=DhF0IIXf61s](url)

**Comment by UriHerrera** [comment]
Can you list the hardware specs of the laptop that you used? @ayvind

**Comment by ayvind** [comment]
intel core i5-8250u 1.6ghz
nvidia geforce mx150
8gb ram

**Comment by UriHerrera** [comment]
I can confirm this bug and at least one variation of it. In my case, the bug varies in that the laptop screen does not load X11 at all, but the external outputs like HDMI and DisplayPort through USB-C work.

Once the system is installed this bug is not present anymore, so it was an exclusive occurrenve in the Live session, meaning that our provided configuration does in fact work, but for some reason in the Live session it does not.

My laptop spcecs.

Intel i7 9750H
Nvidia RTX 2070 Max-Q
16GB RAM
Razer Blade 15 Advanced

**Comment by UriHerrera** [comment]
The current behavior of the released Live ISO is not to include the Nvidia proprietary driver because of this problem, defaulting to Nouveau. As mentioned above, once the system is installed and the users installs the proprietary driver there's no problem.

For the other ISO files (the ones that use OverlayFS) the path that stores the file that `prime-switch` through `gpu-manager` uses to store the information regarding the Optimus hardware in the laptop is enabled now, meaning that the user can switch between them at will

However, during the first boot, the user must select the Intel GT + Nvidia boot entry to login to the desktop and perform `sudo prime-switch nvidia` and reboot. On the second boot, selecting the Generic entry will use the Nvidia card.
