### ISSUE TITLE
Problem in account section

### ISSUE THREAD

**Issue by Jakezys** [Nitrux/nitrux-bug-tracker#152]
I saw that there was already a report for this but it was closed and there is no obvious fix for it there. Basically, when i try to install nitrux i cant press the next button on the page where you create an account. I have tried to install nitrux 5 times now, and only twice did i now have this problem. Thanks

**Comment by UriHerrera** [comment]
It was closed because it was not a bug. 

The release announcement _and_ the tutorial to install the distribution mention the following:

> Calamares will now enforce a stricter user password quality check by using [libpwquality](https://github.com/libpwquality/libpwquality) to increase user account security. When creating the main user account, i.e., the “system administrator,” users must use a password over eight characters long, including uppercase, lowercase, numbers, and symbols, with sufficient randomness when creating their user accounts during installation. Otherwise, the password quality check will be too low, and the installation will not continue.
>
> 🔰 Information: We recommend using a password generator application (mobile or desktop) or a website. Please avoid using simple passwords, i.e., 1234567890aB! Will not pass the password quality checks (the password fails the dictionary check).
>
> ⚠️ Important: We want to emphasize that users can still use insecure user passwords by changing the password for the “system administrator” account post-installation, i.e., the account that Calamares created. We do not recommend doing that, and users who want to do this will have to do it at their own risk. Also, this password policy only affects the account created by Calamares, i.e., the “system administrator,” not other user accounts created by the “system administrator” post-installation.

**Comment by UriHerrera** [comment]
If you're referring to this issue https://github.com/Nitrux/nitrux-bug-tracker/issues/45, It was closed because it was not a reproducible bug. That problem had nothing to do with the password policy implemented in Nitrux 3.2.0 since that issue dates from January 2022.

However, the problem you're probably talking about is the password check, which, as I said earlier, is not a bug, so there's nothing to "fix." The release announcement _and_ the tutorial to install the distribution mention the following:

> Calamares will now enforce a stricter user password quality check by using [libpwquality](https://github.com/libpwquality/libpwquality) to increase user account security. When creating the main user account, i.e., the "system administrator," users must use a password over eight characters long, including uppercase, lowercase, numbers, and symbols, with sufficient randomness when creating their user accounts during installation. Otherwise, the password quality check will be too low, and the installation will not continue.
>
> 🔰 Information: We recommend using a password generator application (mobile or desktop) or a website. Please avoid using simple passwords, i.e., 1234567890aB! Will not pass the password quality checks (the password fails the dictionary check).
>
> ⚠️ Important: We want to emphasize that users can still use insecure user passwords by changing the password for the "system administrator" account post-installation, i.e., the account that Calamares created. We do not recommend doing that, and users who want to do this will have to do it at their own risk. Also, this password policy only affects the account created by Calamares, i.e., the "system administrator," not other user accounts created by the "system administrator" post-installation.

---

That being the case, I'm going to change the title of this issue for accuracy.

**Comment by UriHerrera** [comment]
If you're referring to this issue https://github.com/Nitrux/nitrux-bug-tracker/issues/45, It was closed because it was not a reproducible bug. That problem had nothing to do with the password policy implemented in Nitrux 3.2.0 since that issue dates from January 2022.

However, the problem you're probably talking about in your issue is the password check, which is not a bug, so there's nothing to "fix." The release announcement _and_ the tutorial to install the distribution mention the following:

> Calamares will now enforce a stricter user password quality check by using [libpwquality](https://github.com/libpwquality/libpwquality) to increase user account security. When creating the main user account, i.e., the "system administrator," users must use a password over eight characters long, including uppercase, lowercase, numbers, and symbols, with sufficient randomness when creating their user accounts during installation. Otherwise, the password quality check will be too low, and the installation will not continue.
>
> 🔰 Information: We recommend using a password generator application (mobile or desktop) or a website. Please avoid using simple passwords, i.e., 1234567890aB! Will not pass the password quality checks (the password fails the dictionary check).
>
> ⚠️ Important: We want to emphasize that users can still use insecure user passwords by changing the password for the "system administrator" account post-installation, i.e., the account that Calamares created. We do not recommend doing that, and users who want to do this will have to do it at their own risk. Also, this password policy only affects the account created by Calamares, i.e., the "system administrator," not other user accounts created by the "system administrator" post-installation.

---

That being the case, I'm going to change the title of this issue for accuracy.
