### ISSUE TITLE
Blank screen with cursor 

### ISSUE THREAD

**Issue by Vinnyt-droid** [Nitrux/nitrux-bug-tracker#186]
# Issue Description

Sometimes (randomly)  when closing browsers or apps my screen goes black with a mouse cursor.
My only option is to hold the power button to shut my laptop down.

**Steps to reproduce the bug**

1. Click on "X" on the top bar or right click on the app icon on the taskbar and select close.
This is a random occurrence and does not always happen.

**Expected behavior**

Browser or app should close.

**Screenshots**

Not able to take screenshot.

**Videos**

No way to video this.

**Additional context**

I reinstalled Nitrux with the latest version and this made no difference.

Operating System: Nitrux 3.5.1 build.300624.nm
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.9.7-1-liquorix-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 20 × 13th Gen Intel® Core™ i7-13700H
Memory: 15.3 GiB of DDR5 RAM
Graphics Processor: Mesa Intel® Graphics ( also has  NVIDIA graphics)
Manufacturer: Micro-Star International Co., Ltd.
Product Name: Creator M16 B13VE
System Version: REV:1.0

**Comment by UriHerrera** [comment]
Read the [Troubleshooting](https://nxos.org/tutorial/using-nitrux-nx-desktop/#troubleshooting) section in the tutorial, Using Nitrux: NX Desktop.

Also, remove the item "NX Networks"—which is deprecated—from the system tray and use the one Plasma provides.

---

The next release includes a script to keep Plasma alive.

---

I'm closing the issue since a workaround has been provided.
