### ISSUE TITLE
Cannot sync with timeserver

### ISSUE THREAD

**Issue by linux-leo** [Nitrux/nitrux-bug-tracker#66]
**Describe the bug**
I open the settings menu for date and time, but can only set the time manually and not sync it with a timeserver

**To Reproduce**
1. Go to System Settings
2. Click on Regional Settings
3. Go down to Date and Time

**Expected behavior**
It works

**Desktop (please complete the following information):**

 - OS: Nitrux
 - Version: 2.1.1

**Additional context**
I upgraded to Nitrux 2.1.1, but the issue was there before.

**Screenshots*
![Screenshot_20220506_134456](https://user-images.githubusercontent.com/63003858/167125824-1799dd87-dc8c-42f2-ba17-35acc26803a7.png)
*

**Comment by UriHerrera** [comment]
The problem occurs because Plasma uses [timedated](https://www.freedesktop.org/wiki/Software/systemd/timedated/) when the user checks the checkbox <kbd>Set date and time automatically</kbd>. The error specifically is:

```
ntpUtility = "/usr/bin/ntpupdate"
Timedated not found, using legacy saving mode
```

The binary `timedated` is a component of systemd (found in `/lib/systemd/systemd-timedated`), since it's unavailable in the distribution to Plasma you see the error message.
