### ISSUE TITLE
Quick bug report after Nitrux 2.2.0 fresh installation

### ISSUE THREAD

**Issue by lfom** [Nitrux/nitrux-bug-tracker#73]
I have just installed Nitrux 2.2.0 on a notebook, and this is a quick report of some issues I have found. Please feel free to ask for more info or to open separated issues if this will help tracking them. They are not in any specific order or priority.

1. Update issues: Nitrux uses `pkcon` to manage updates, but it works differently than other package managers, so it would be nice to have some tips or a guide about how to update the system, and/or a GUI tool for update notifications. I had some errors (29 IIRIC) related to some packages (I think it was iproute5 or something like this) when I tried to refresh and then update, but they were fixed after following the guide to update the distro from the previous version to 2.2.0
2. Searching for packages/apps does not work: the GUI for installing apps simply shows the spinning animation forever when searching for something that is not not available (I think so because it works when I searched for GIMP, for instance), and the same happens with `pkcon search`. Maybe it is related?
3. Oddly, launching downloaded AppImages did not work OOTB, I got a notification to install FUSE, which was already installed. It was fixed after I followed the instructions in the link provided by the notification and added a **fuse** group and added my user to it.
4. I could install Steam using the provided item from the app grid, but launched an imported game to my library did not work, it just showed that something crashed. I did not try to install a game from my Steam library tho
5. Heroic AppImage did not work either, probably it requires a 32-bits WINE installation. The Flatpak version seemed to work fine
6. For some reason, some app dialogs and new windows were very small and needed to be resized to be used properly (MAUI bug?)
7. Some default settings are kinda annoying for desktop users: no tap to click using the trackpad, and one click to open stuff in the file manager
8. Index has a list view but it shows no info besides the file/dir name, and I could not find "paste" in the menu either
9. The page in the nxos.org blog says Nitrux come with a pre-installed WINE version that is supposed to support 32-bits applications, but it was not the case. I could install WINE using `pkcon` but it did not have support for 32-bits app. This can be a deal breaker for many users

Thanks for creating and maintaining the distro!

Regards

**Comment by UriHerrera** [comment]
We appreciate your feedback; however, please create one issue for each problem.

----

1. PackageKit has extensive documentation on its website. Also, running `man pkcon` will provide you with its manual, or also simply typing `pkcon` and pressing <kbd>Enter</kbd> will display its subcommand (as the message in the terminal instructs). As a new user, you don't know, but I'll explain why you get these errors. Debian focuses on using `systemd` and `systemctl` extensively in the maintainer scripts for its packages; **we do not use systemd**. While we include the binary `systemctl`, it's a standalone binary made for containers and does not manage absolutely anything in the distribution. However, having it prevents `dpkg` from freaking out, and it will only display a message in its output. To effectively dismiss that error message, you need to run `pkcon repair`, which you did by following those instructions.
2. Yes, **the NX Software Center does not manage Debian packages**. _That is not a bug_, and we have often emphasized its purpose; I should add that it does not manage Debian packages and will not do that as its explicit purpose is to manage AppImages exclusively. Also, if searches take time to load, it's due to either your connection or your connection to AppImageHub.com and AppRepo.de, the websites the Software Center uses to list content. We can't "fix" either.
3. See https://github.com/Nitrux/nitrux-bug-tracker/issues/71.
4. We do not develop Steam, Flatpak, or the Steam Flatpak. Please create an issue at their respective bug trackers.
5. Like above, we do not create or maintain the AppImage of Heroic Launcher. Please create an issue at their respective bug tracker.
6. IMO, not an issue.
7. KDE sets trackpad settings; if you think the default settings are wrong, create an issue at their bug tracker. Users can change the behavior of opening directories in System Settings if they don't like the default option of single-click.
8. Index does not list the information in the list view because it's a list view, not a details view (they are different concepts). The paste command is in the same menu where you changed the views; it's the first group of items at the top that have the label **Edit**. Paste also works by right-clicking an item and pasting somewhere.
9. The tutorial is outdated. We did mention many releases ago that we were not going to include the AppImage of WIne we were using anymore because it had been unmaintained for a very long time. Specifically, we mentioned this on the 29th of January. And as we mention in the Notes, we recommend Bottles instead.
