### ISSUE TITLE
Dependency problems after applying package updates

### ISSUE THREAD

**Issue by KewlToyZ** [Nitrux/nitrux-bug-tracker#8]
**Describe the bug**
Latest ISO - Automatic Updates break the OS by default even without installing.
Installation does the same thing from hard drive.

Automatic updates break the DE and make it unusable. The DE can not find any of its libraries after updates. Reboot, the DE just gives a blinking cursor and never moves. Never shuts down.

**To Reproduce**
1. Go to '...' Download latest ISO from Nitrux OS Website:
https://nxos.org/download/latest/

Run the ISO from USB as Live to install OS. Explore the OS casually without making changes.
The DE Notifies the user there is an update available.
Get all updates, let them install. 

DE can no longer see any of its libraries. Can't send feedback or view applications.

**Expected behavior**
DE will no longer run after reboot. Just mouse cursor and empty DE with access to terminal and looking glass. All libraries are not found. Recovery doesn't work in either kernel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Nitrux latest download
 - Browser Firefox
 - Version
 - etc.

**Additional context**
I just wanted to use the OS. It seems to have the layout and configuration tools I have been wanting in a Distro. The installer is polished so much better than any other I've used. Especially the drive artitioning for multi boot setup. It told me what I'm actually looking at instead of making me guess.
I'm really disappointed I can't use this distro after it self destructs.  I would love to know when I can use it. Looks like a very beautiful project.

**Comment by UriHerrera** [comment]
Hi. I just installed it, and at the time of doing `apt upgrade`, the new packages are installed without a problem. 

Restart, and everything work fine. 

Now, then I run `apt dist-upgrade`, and there is a dependency resolution problem, first by KDE Partition Manager that updates a library that it uses (`libkpmcore8` to `libkpmcore9`), so first it is to update that, run `apt install partitionmanager --only-upgrade` and then you have to update the `plasma-desktop` package and this is where the other problem is since the new package depends on one called `ibus-table-emoji` and when you want to install this APT wants to remove others that it should not touch (because #APT ). 

So to update Plasma, you have to solve that problem.

First, there is to downgrade `gir1.2-glib-2.0` to version 1.56.1-1 so run 

- `apt install gir1.2-glib-2.0=1.56.1-1`

Second, you must force the update of `libdconf1` to version 0.26.0-ubuntu3 since APT cannot solve this without removing practically everything, so run 

- `apt download libdconf1=0.26.0-2ubuntu3` and then

-  `dpkg --force-all -i libdconf1_0.26.0-2ubuntu3_amd64.deb` to force the package installation.

Third, it is necessary to force the downgrade of two other packages, `dconf-gsettings-backend` and `dconf-service`, so you still have to download them, run 

- `apt download dconf-gsettings-backend=0.26.0-2ubuntu3 dconf-service=0.26.0-2ubuntu3` and install them with 

- `dpkg --force-all -i dconf-gsettings-backend_0.26.0-2ubuntu3_amd64.deb dconf-service_0.26.0-2ubuntu3_amd64.deb`

Fourth, you have to make sure that there is nothing else missing, so running `apt install --fix-broken` should not give any errors.

And finally, `plasma-desktop` can be updated. To upgrade it run
- `apt install plasma-desktop --only-upgrade --no-install-recommends`

**Comment by KewlToyZ** [comment]
Thanks Uri! I will give it a try. I don't want to be a pest. I'm just really intrigued by your interface and enjoy tinkering around. There is a lot of polish to your packaging of it I really liked over the other Plasma DE's. I noticed that one of your team did some updates Saturday on Github and the iso was available for download again. I grabbed it and reinstalled it. Right away I avoided updates period. Mainly I noticed the interface wanted to delete NX libraries first thing. So I was wondering what libraries I should block from changes as components of the NX interface DE. 
I've submitted a few KDE crash reports with the Global theme switching. Checkbox on Use Layout from Theme causes a crash. 
I also noticed the Enter key does not work on the Login Screen. I have to use the mouse or touch screen to click the Unlock button.
Panel font colors are not connected to the themes, or colors assigned.
Again thank you for your time and your project!

**Comment by UriHerrera** [comment]
The commands above will solve the problem in a fresh installation. So, before using Discover for anything, execute them.

You don't need to hold any packages.

For other issues, please make a separate issue.

**Comment by KewlToyZ** [comment]
Thanks again Uri! I had to read the steps a bit more literally. I needed to run the sudo apt upgrade first.
If I had a line error out, I ran it again and it worked without the extra restarts. And I definitely missed the Third step which gave me problems. I started over again and it worked fine now. Should I continue using the nomad-dektop repo? I tried `deb [trusted=yes] https://repo.nxos.org/ubuntu/repos/nomad-desktop nxos main` but it still denies it on sudo apt update.

**Comment by UriHerrera** [comment]
> Thanks again Uri! I had to read the steps a bit more literally. I needed to run the sudo apt upgrade first.
> If I had a line error out, I ran it again and it worked without the extra restarts. And I definitely missed the Third step which gave me problems. I started over again and it worked fine now. Should I continue using the nomad-dektop repo? I tried `deb [trusted=yes] https://repo.nxos.org/ubuntu/repos/nomad-desktop nxos main` but it still denies it on sudo apt update.

We've changed the repository URL, you can remove that one and replace it with:

```
deb https://repo.nxos.org/nitrux/ nitrux main

```

**Comment by UriHerrera** [comment]
Closing as this issue only affects `nitrux-stable-amd64_01022020.iso`, `nitrux-stable-amd64_2020.02.28.iso` is available and does not present this issue.

**Comment by KewlToyZ** [comment]
No problems in 2020.02.28 worked like a dream. Thanks Uri!
